////////////////////////////////////////////////////////////////////////////////
// 
// WARNING - DO NOT EDIT THIS FILE
//
// These data objects are generated from the database.  If you need to add 
// properties, please update the database, then re-generate.
//
////////////////////////////////////////////////////////////////////////////////

if(!inc)
	var inc = {};
if(!inc.accounting)
	inc.accounting = {};
if(!inc.accounting.data)
	inc.accounting.data = {};

new function() {
	inc.accounting.data.UserRow = function() {
		var obj = new inc.data.Row();

		obj.getGuid = function() { return obj.get("GUID"); };
		obj.setGuid = function(value) { obj.set("GUID", value); };

		obj.getIsAllowed = function() { return obj.get("Is Allowed"); };
		obj.setIsAllowed = function(value) { obj.set("Is Allowed", value); };

		obj.getDisplayName = function() { return obj.get("Display Name"); };
		obj.setDisplayName = function(value) { obj.set("Display Name", value); };

		obj.getEmailAddress = function() { return obj.get("Email Address"); };
		obj.setEmailAddress = function(value) { obj.set("Email Address", value); };

		obj.getPasswordDate = function() { return obj.get("Password Date"); };
		obj.setPasswordDate = function(value) { obj.set("Password Date", value); };

		obj.getPasswordHash = function() { return obj.get("Password Hash"); };
		obj.setPasswordHash = function(value) { obj.set("Password Hash", value); };

		obj.getEmployeesGUID = function() { return obj.get("Employees GUID"); };
		obj.setEmployeesGUID = function(value) { obj.set("Employees GUID", value); };

		return obj;
	};
};


