////////////////////////////////////////////////////////////////////////////////
// 
// WARNING - DO NOT EDIT THIS FILE
//
// These data objects are generated from the database.  If you need to add 
// properties, please update the database, then re-generate.
//
////////////////////////////////////////////////////////////////////////////////
if(!inc)
	var inc = {};
if(!inc.accounting)
	inc.accounting = {};
if(!inc.accounting.data)
	inc.accounting.data = {};

new function() {
	inc.accounting.data.PayrollChecksRow = function() {
		var obj = new inc.data.Row();

				
		/*
		 * @type java.lang.String
		 */
		obj.getGuid = function() { return obj.get("GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setGuid = function(value) { obj.set("GUID", value); };
		
				
		/*
		 * @type java.lang.Boolean
		 */
		obj.getIsTemplate = function() { return obj.get("Is Template"); };
		/*
		 * @param java.lang.Boolean value 
		 */
		obj.setIsTemplate = function(value) { obj.set("Is Template", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getNumber = function() { return obj.get("Number"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setNumber = function(value) { obj.set("Number", value); };
		
				
		/*
		 * @type java.util.Date
		 */
		obj.getDate = function() { return obj.get("Date"); };
		/*
		 * @param java.util.Date value 
		 */
		obj.setDate = function(value) { obj.set("Date", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getEmployeesGuid = function() { return obj.get("Employees GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setEmployeesGuid = function(value) { obj.set("Employees GUID", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getPayToTheOrderOf = function() { return obj.get("Pay To The Order Of"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setPayToTheOrderOf = function(value) { obj.set("Pay To The Order Of", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getLine1 = function() { return obj.get("Line 1"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setLine1 = function(value) { obj.set("Line 1", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getLine2 = function() { return obj.get("Line 2"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setLine2 = function(value) { obj.set("Line 2", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getCountry = function() { return obj.get("Country"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setCountry = function(value) { obj.set("Country", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getCity = function() { return obj.get("City"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setCity = function(value) { obj.set("City", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getState = function() { return obj.get("State"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setState = function(value) { obj.set("State", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getPostalCode = function() { return obj.get("Postal Code"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setPostalCode = function(value) { obj.set("Postal Code", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getAccountsGuid = function() { return obj.get("Accounts GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setAccountsGuid = function(value) { obj.set("Accounts GUID", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getPostedTransactionsGuid = function() { return obj.get("Posted Transactions GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setPostedTransactionsGuid = function(value) { obj.set("Posted Transactions GUID", value); };
		
				
		/*
		 * @type java.math.BigDecimal
		 */
		obj.getCompensation = function() { return obj.get("Compensation"); };
		/*
		 * @param java.math.BigDecimal value 
		 */
		obj.setCompensation = function(value) { obj.set("Compensation", value); };
		
				
		/*
		 * @type java.math.BigDecimal
		 */
		obj.getAdjustedGross = function() { return obj.get("Adjusted Gross"); };
		/*
		 * @param java.math.BigDecimal value 
		 */
		obj.setAdjustedGross = function(value) { obj.set("Adjusted Gross", value); };
		
				
		/*
		 * @type java.math.BigDecimal
		 */
		obj.getEmployeePaid = function() { return obj.get("Employee Paid"); };
		/*
		 * @param java.math.BigDecimal value 
		 */
		obj.setEmployeePaid = function(value) { obj.set("Employee Paid", value); };
		
				
		/*
		 * @type java.math.BigDecimal
		 */
		obj.getPaycheckAmount = function() { return obj.get("Paycheck Amount"); };
		/*
		 * @param java.math.BigDecimal value 
		 */
		obj.setPaycheckAmount = function(value) { obj.set("Paycheck Amount", value); };
		
				
		/*
		 * @type java.math.BigDecimal
		 */
		obj.getCompanyPaid = function() { return obj.get("Company Paid"); };
		/*
		 * @param java.math.BigDecimal value 
		 */
		obj.setCompanyPaid = function(value) { obj.set("Company Paid", value); };
		
				
		/*
		 * @type java.math.BigDecimal
		 */
		obj.getTotalCosts = function() { return obj.get("Total Costs"); };
		/*
		 * @param java.math.BigDecimal value 
		 */
		obj.setTotalCosts = function(value) { obj.set("Total Costs", value); };
		
				
		/*
		 * @type java.lang.Integer
		 */
		obj.getDuration = function() { return obj.get("Duration"); };
		/*
		 * @param java.lang.Integer value 
		 */
		obj.setDuration = function(value) { obj.set("Duration", value); };
		
				
		/*
		 * @type java.util.Date
		 */
		obj.getEnding = function() { return obj.get("Ending"); };
		/*
		 * @param java.util.Date value 
		 */
		obj.setEnding = function(value) { obj.set("Ending", value); };
		
		

		return obj;
	};
};