////////////////////////////////////////////////////////////////////////////////
// 
// WARNING - DO NOT EDIT THIS FILE
//
// These data objects are generated from the database.  If you need to add 
// properties, please update the database, then re-generate.
//
////////////////////////////////////////////////////////////////////////////////
if(!inc)
	var inc = {};
if(!inc.accounting)
	inc.accounting = {};
if(!inc.accounting.data)
	inc.accounting.data = {};

new function() {
	inc.accounting.data.PermissionsRow = function() {
		var obj = new inc.data.Row();

				
		/*
		 * @type java.lang.String
		 */
		obj.getGroupsGuid = function() { return obj.get("Groups GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setGroupsGuid = function(value) { obj.set("Groups GUID", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getSecurablesGuid = function() { return obj.get("Securables GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setSecurablesGuid = function(value) { obj.set("Securables GUID", value); };
		
				
		/*
		 * @type java.lang.Boolean
		 */
		obj.getCanCreate = function() { return obj.get("Can Create"); };
		/*
		 * @param java.lang.Boolean value 
		 */
		obj.setCanCreate = function(value) { obj.set("Can Create", value); };
		
				
		/*
		 * @type java.lang.Boolean
		 */
		obj.getCanRead = function() { return obj.get("Can Read"); };
		/*
		 * @param java.lang.Boolean value 
		 */
		obj.setCanRead = function(value) { obj.set("Can Read", value); };
		
				
		/*
		 * @type java.lang.Boolean
		 */
		obj.getCanUpdate = function() { return obj.get("Can Update"); };
		/*
		 * @param java.lang.Boolean value 
		 */
		obj.setCanUpdate = function(value) { obj.set("Can Update", value); };
		
				
		/*
		 * @type java.lang.Boolean
		 */
		obj.getCanDelete = function() { return obj.get("Can Delete"); };
		/*
		 * @param java.lang.Boolean value 
		 */
		obj.setCanDelete = function(value) { obj.set("Can Delete", value); };
		
		

		return obj;
	};
};