////////////////////////////////////////////////////////////////////////////////
// 
// WARNING - DO NOT EDIT THIS FILE
//
// These data objects are generated from the database.  If you need to add 
// properties, please update the database, then re-generate.
//
////////////////////////////////////////////////////////////////////////////////
if(!inc)
	var inc = {};
if(!inc.accounting)
	inc.accounting = {};
if(!inc.accounting.data)
	inc.accounting.data = {};

new function() {
	inc.accounting.data.TransactionLinesRow = function() {
		var obj = new inc.data.Row();

				
		/*
		 * @type java.lang.String
		 */
		obj.getGuid = function() { return obj.get("GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setGuid = function(value) { obj.set("GUID", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getTransactionsGuid = function() { return obj.get("Transactions GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setTransactionsGuid = function(value) { obj.set("Transactions GUID", value); };
		
				
		/*
		 * @type java.lang.Integer
		 */
		obj.getSortOrder = function() { return obj.get("Sort Order"); };
		/*
		 * @param java.lang.Integer value 
		 */
		obj.setSortOrder = function(value) { obj.set("Sort Order", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getDescription = function() { return obj.get("Description"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setDescription = function(value) { obj.set("Description", value); };
		
				
		/*
		 * @type java.math.BigDecimal
		 */
		obj.getDebit = function() { return obj.get("Debit"); };
		/*
		 * @param java.math.BigDecimal value 
		 */
		obj.setDebit = function(value) { obj.set("Debit", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getJobsGuid = function() { return obj.get("Jobs GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setJobsGuid = function(value) { obj.set("Jobs GUID", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getDepartmentsGuid = function() { return obj.get("Departments GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setDepartmentsGuid = function(value) { obj.set("Departments GUID", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getAccountsGuid = function() { return obj.get("Accounts GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setAccountsGuid = function(value) { obj.set("Accounts GUID", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getReconciliationsGuid = function() { return obj.get("Reconciliations GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setReconciliationsGuid = function(value) { obj.set("Reconciliations GUID", value); };
		
		

		return obj;
	};
};