////////////////////////////////////////////////////////////////////////////////
// 
// WARNING - DO NOT EDIT THIS FILE
//
// These data objects are generated from the database.  If you need to add 
// properties, please update the database, then re-generate.
//
////////////////////////////////////////////////////////////////////////////////
if(!inc)
	var inc = {};
if(!inc.accounting)
	inc.accounting = {};
if(!inc.accounting.data)
	inc.accounting.data = {};

new function() {
	inc.accounting.data.TransactionTypesRow = function() {
		var obj = new inc.data.Row();

				
		/*
		 * @type java.lang.String
		 */
		obj.getGuid = function() { return obj.get("GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setGuid = function(value) { obj.set("GUID", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getName = function() { return obj.get("Name"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setName = function(value) { obj.set("Name", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getEditUrl = function() { return obj.get("Edit URL"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setEditUrl = function(value) { obj.set("Edit URL", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getListUrl = function() { return obj.get("List URL"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setListUrl = function(value) { obj.set("List URL", value); };
		
				
		/*
		 * @type java.lang.Boolean
		 */
		obj.getIsAllowed = function() { return obj.get("Is Allowed"); };
		/*
		 * @param java.lang.Boolean value 
		 */
		obj.setIsAllowed = function(value) { obj.set("Is Allowed", value); };
		
		

		return obj;
	};
};