////////////////////////////////////////////////////////////////////////////////
// 
// WARNING - DO NOT EDIT THIS FILE
//
// These data objects are generated from the database.  If you need to add 
// properties, please update the database, then re-generate.
//
////////////////////////////////////////////////////////////////////////////////
if(!inc)
	var inc = {};
if(!inc.accounting)
	inc.accounting = {};
if(!inc.accounting.data)
	inc.accounting.data = {};

new function() {
	inc.accounting.data.UnitMeasuresRow = function() {
		var obj = new inc.data.Row();

				
		/*
		 * @type java.lang.String
		 */
		obj.getGuid = function() { return obj.get("GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setGuid = function(value) { obj.set("GUID", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getDisplayName = function() { return obj.get("Display Name"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setDisplayName = function(value) { obj.set("Display Name", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getAbbreviation = function() { return obj.get("Abbreviation"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setAbbreviation = function(value) { obj.set("Abbreviation", value); };
		
				
		/*
		 * @type java.lang.Boolean
		 */
		obj.getIsAllowed = function() { return obj.get("Is Allowed"); };
		/*
		 * @param java.lang.Boolean value 
		 */
		obj.setIsAllowed = function(value) { obj.set("Is Allowed", value); };
		
		

		return obj;
	};
};