////////////////////////////////////////////////////////////////////////////////
// 
// WARNING - DO NOT EDIT THIS FILE
//
// These data objects are generated from the database.  If you need to add 
// properties, please update the database, then re-generate.
//
////////////////////////////////////////////////////////////////////////////////
if(!inc)
	var inc = {};
if(!inc.accounting)
	inc.accounting = {};
if(!inc.accounting.data)
	inc.accounting.data = {};

new function() {
	inc.accounting.data.ContactsRow = function() {
		var obj = new inc.data.Row();

				
		/*
		 * @type java.lang.String
		 */
		obj.getGuid = function() { return obj.get("GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setGuid = function(value) { obj.set("GUID", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getParentContactsGuid = function() { return obj.get("Parent Contacts GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setParentContactsGuid = function(value) { obj.set("Parent Contacts GUID", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getDisplayName = function() { return obj.get("Display Name"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setDisplayName = function(value) { obj.set("Display Name", value); };
		
				
		/*
		 * @type java.lang.Boolean
		 */
		obj.getIsAllowed = function() { return obj.get("Is Allowed"); };
		/*
		 * @param java.lang.Boolean value 
		 */
		obj.setIsAllowed = function(value) { obj.set("Is Allowed", value); };
		
				
		/*
		 * @type java.util.Date
		 */
		obj.getContactSince = function() { return obj.get("Contact Since"); };
		/*
		 * @param java.util.Date value 
		 */
		obj.setContactSince = function(value) { obj.set("Contact Since", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getDefaultShippingContactsGuid = function() { return obj.get("Default Shipping Contacts GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setDefaultShippingContactsGuid = function(value) { obj.set("Default Shipping Contacts GUID", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getWebsite = function() { return obj.get("Website"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setWebsite = function(value) { obj.set("Website", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getEmailAddress = function() { return obj.get("Email Address"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setEmailAddress = function(value) { obj.set("Email Address", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getOfficePhone = function() { return obj.get("Office Phone"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setOfficePhone = function(value) { obj.set("Office Phone", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getMobilePhone = function() { return obj.get("Mobile Phone"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setMobilePhone = function(value) { obj.set("Mobile Phone", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getHomePhone = function() { return obj.get("Home Phone"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setHomePhone = function(value) { obj.set("Home Phone", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getFaxNumber = function() { return obj.get("Fax Number"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setFaxNumber = function(value) { obj.set("Fax Number", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getLine1 = function() { return obj.get("Line 1"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setLine1 = function(value) { obj.set("Line 1", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getLine2 = function() { return obj.get("Line 2"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setLine2 = function(value) { obj.set("Line 2", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getCountry = function() { return obj.get("Country"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setCountry = function(value) { obj.set("Country", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getCity = function() { return obj.get("City"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setCity = function(value) { obj.set("City", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getState = function() { return obj.get("State"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setState = function(value) { obj.set("State", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getPostalCode = function() { return obj.get("Postal Code"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setPostalCode = function(value) { obj.set("Postal Code", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getTaxGroupGuid = function() { return obj.get("Tax Group GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setTaxGroupGuid = function(value) { obj.set("Tax Group GUID", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getContactTypesGuid = function() { return obj.get("Contact Types GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setContactTypesGuid = function(value) { obj.set("Contact Types GUID", value); };
		
		

		return obj;
	};
};