////////////////////////////////////////////////////////////////////////////////
// 
// WARNING - DO NOT EDIT THIS FILE
//
// These data objects are generated from the database.  If you need to add 
// properties, please update the database, then re-generate.
//
////////////////////////////////////////////////////////////////////////////////
if(!inc)
	var inc = {};
if(!inc.accounting)
	inc.accounting = {};
if(!inc.accounting.data)
	inc.accounting.data = {};

new function() {
	inc.accounting.data.ContactNotesRow = function() {
		var obj = new inc.data.Row();

				
		/*
		 * @type java.lang.String
		 */
		obj.getGuid = function() { return obj.get("GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setGuid = function(value) { obj.set("GUID", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getContactsGuid = function() { return obj.get("Contacts GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setContactsGuid = function(value) { obj.set("Contacts GUID", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getUsersGuid = function() { return obj.get("Users GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setUsersGuid = function(value) { obj.set("Users GUID", value); };
		
				
		/*
		 * @type java.util.Date
		 */
		obj.getDated = function() { return obj.get("Dated"); };
		/*
		 * @param java.util.Date value 
		 */
		obj.setDated = function(value) { obj.set("Dated", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getSubject = function() { return obj.get("Subject"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setSubject = function(value) { obj.set("Subject", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getMemorandum = function() { return obj.get("Memorandum"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setMemorandum = function(value) { obj.set("Memorandum", value); };
		
		

		return obj;
	};
};