////////////////////////////////////////////////////////////////////////////////
// 
// WARNING - DO NOT EDIT THIS FILE
//
// These data objects are generated from the database.  If you need to add 
// properties, please update the database, then re-generate.
//
////////////////////////////////////////////////////////////////////////////////
if(!inc)
	var inc = {};
if(!inc.accounting)
	inc.accounting = {};
if(!inc.accounting.data)
	inc.accounting.data = {};

new function() {
	inc.accounting.data.DepartmentsRow = function() {
		var obj = new inc.data.Row();

				
		/*
		 * @type java.lang.String
		 */
		obj.getGuid = function() { return obj.get("GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setGuid = function(value) { obj.set("GUID", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getParentDepartmentsGuid = function() { return obj.get("Parent Departments GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setParentDepartmentsGuid = function(value) { obj.set("Parent Departments GUID", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getSegment = function() { return obj.get("Segment"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setSegment = function(value) { obj.set("Segment", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getNumber = function() { return obj.get("Number"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setNumber = function(value) { obj.set("Number", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getName = function() { return obj.get("Name"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setName = function(value) { obj.set("Name", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getNestedName = function() { return obj.get("Nested Name"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setNestedName = function(value) { obj.set("Nested Name", value); };
		
				
		/*
		 * @type java.lang.Boolean
		 */
		obj.getIsAllowed = function() { return obj.get("Is Allowed"); };
		/*
		 * @param java.lang.Boolean value 
		 */
		obj.setIsAllowed = function(value) { obj.set("Is Allowed", value); };
		
		

		return obj;
	};
};