////////////////////////////////////////////////////////////////////////////////
// 
// WARNING - DO NOT EDIT THIS FILE
//
// These data objects are generated from the database.  If you need to add 
// properties, please update the database, then re-generate.
//
////////////////////////////////////////////////////////////////////////////////
if(!inc)
	var inc = {};
if(!inc.accounting)
	inc.accounting = {};
if(!inc.accounting.data)
	inc.accounting.data = {};

new function() {
	inc.accounting.data.DocumentsRow = function() {
		var obj = new inc.data.Row();

				
		/*
		 * @type java.lang.String
		 */
		obj.getGuid = function() { return obj.get("GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setGuid = function(value) { obj.set("GUID", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getDocumentTypesGuid = function() { return obj.get("Document Types GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setDocumentTypesGuid = function(value) { obj.set("Document Types GUID", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getParentDocumentsGuid = function() { return obj.get("Parent Documents GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setParentDocumentsGuid = function(value) { obj.set("Parent Documents GUID", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getReferenceNumber = function() { return obj.get("Reference Number"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setReferenceNumber = function(value) { obj.set("Reference Number", value); };
		
				
		/*
		 * @type java.util.Date
		 */
		obj.getDate = function() { return obj.get("Date"); };
		/*
		 * @param java.util.Date value 
		 */
		obj.setDate = function(value) { obj.set("Date", value); };
		
				
		/*
		 * @type java.util.Date
		 */
		obj.getDueDate = function() { return obj.get("Due Date"); };
		/*
		 * @param java.util.Date value 
		 */
		obj.setDueDate = function(value) { obj.set("Due Date", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getPostedAccountsGuid = function() { return obj.get("Posted Accounts GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setPostedAccountsGuid = function(value) { obj.set("Posted Accounts GUID", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getPostedTransactionsGuid = function() { return obj.get("Posted Transactions GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setPostedTransactionsGuid = function(value) { obj.set("Posted Transactions GUID", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getContactsGuid = function() { return obj.get("Contacts GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setContactsGuid = function(value) { obj.set("Contacts GUID", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getContactsDisplayName = function() { return obj.get("Contacts Display Name"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setContactsDisplayName = function(value) { obj.set("Contacts Display Name", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getCustomerReference = function() { return obj.get("Customer Reference"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setCustomerReference = function(value) { obj.set("Customer Reference", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getTerms = function() { return obj.get("Terms"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setTerms = function(value) { obj.set("Terms", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getShippingMethod = function() { return obj.get("Shipping Method"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setShippingMethod = function(value) { obj.set("Shipping Method", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getShippingNumber = function() { return obj.get("Shipping Number"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setShippingNumber = function(value) { obj.set("Shipping Number", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getBillingContactsGuid = function() { return obj.get("Billing Contacts GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setBillingContactsGuid = function(value) { obj.set("Billing Contacts GUID", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getBillingAddressDisplayName = function() { return obj.get("Billing Address Display Name"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setBillingAddressDisplayName = function(value) { obj.set("Billing Address Display Name", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getBillingAddressLine1 = function() { return obj.get("Billing Address Line 1"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setBillingAddressLine1 = function(value) { obj.set("Billing Address Line 1", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getBillingAddressLine2 = function() { return obj.get("Billing Address Line 2"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setBillingAddressLine2 = function(value) { obj.set("Billing Address Line 2", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getBillingAddressCity = function() { return obj.get("Billing Address City"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setBillingAddressCity = function(value) { obj.set("Billing Address City", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getBillingAddressState = function() { return obj.get("Billing Address State"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setBillingAddressState = function(value) { obj.set("Billing Address State", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getBillingAddressPostalCode = function() { return obj.get("Billing Address Postal Code"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setBillingAddressPostalCode = function(value) { obj.set("Billing Address Postal Code", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getBillingAddressCountry = function() { return obj.get("Billing Address Country"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setBillingAddressCountry = function(value) { obj.set("Billing Address Country", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getShippingContactsGuid = function() { return obj.get("Shipping Contacts GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setShippingContactsGuid = function(value) { obj.set("Shipping Contacts GUID", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getShippingAddressDisplayName = function() { return obj.get("Shipping Address Display Name"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setShippingAddressDisplayName = function(value) { obj.set("Shipping Address Display Name", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getShippingAddressLine1 = function() { return obj.get("Shipping Address Line 1"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setShippingAddressLine1 = function(value) { obj.set("Shipping Address Line 1", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getShippingAddressLine2 = function() { return obj.get("Shipping Address Line 2"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setShippingAddressLine2 = function(value) { obj.set("Shipping Address Line 2", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getShippingAddressCity = function() { return obj.get("Shipping Address City"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setShippingAddressCity = function(value) { obj.set("Shipping Address City", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getShippingAddressState = function() { return obj.get("Shipping Address State"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setShippingAddressState = function(value) { obj.set("Shipping Address State", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getShippingAddressPostalCode = function() { return obj.get("Shipping Address Postal Code"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setShippingAddressPostalCode = function(value) { obj.set("Shipping Address Postal Code", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getShippingAddressCountry = function() { return obj.get("Shipping Address Country"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setShippingAddressCountry = function(value) { obj.set("Shipping Address Country", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getSalesTaxesGuid = function() { return obj.get("Sales Taxes GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setSalesTaxesGuid = function(value) { obj.set("Sales Taxes GUID", value); };
		
				
		/*
		 * @type java.math.BigDecimal
		 */
		obj.getTaxableSubtotal = function() { return obj.get("Taxable Subtotal"); };
		/*
		 * @param java.math.BigDecimal value 
		 */
		obj.setTaxableSubtotal = function(value) { obj.set("Taxable Subtotal", value); };
		
				
		/*
		 * @type java.math.BigDecimal
		 */
		obj.getNontaxableSubtotal = function() { return obj.get("Nontaxable Subtotal"); };
		/*
		 * @param java.math.BigDecimal value 
		 */
		obj.setNontaxableSubtotal = function(value) { obj.set("Nontaxable Subtotal", value); };
		
				
		/*
		 * @type java.math.BigDecimal
		 */
		obj.getTaxRate = function() { return obj.get("Tax Rate"); };
		/*
		 * @param java.math.BigDecimal value 
		 */
		obj.setTaxRate = function(value) { obj.set("Tax Rate", value); };
		
				
		/*
		 * @type java.math.BigDecimal
		 */
		obj.getSubtotal = function() { return obj.get("Subtotal"); };
		/*
		 * @param java.math.BigDecimal value 
		 */
		obj.setSubtotal = function(value) { obj.set("Subtotal", value); };
		
				
		/*
		 * @type java.math.BigDecimal
		 */
		obj.getTaxes = function() { return obj.get("Taxes"); };
		/*
		 * @param java.math.BigDecimal value 
		 */
		obj.setTaxes = function(value) { obj.set("Taxes", value); };
		
				
		/*
		 * @type java.math.BigDecimal
		 */
		obj.getTotal = function() { return obj.get("Total"); };
		/*
		 * @param java.math.BigDecimal value 
		 */
		obj.setTotal = function(value) { obj.set("Total", value); };
		
		

		return obj;
	};
};