////////////////////////////////////////////////////////////////////////////////
// 
// WARNING - DO NOT EDIT THIS FILE
//
// These data objects are generated from the database.  If you need to add 
// properties, please update the database, then re-generate.
//
////////////////////////////////////////////////////////////////////////////////
if(!inc)
	var inc = {};
if(!inc.accounting)
	inc.accounting = {};
if(!inc.accounting.data)
	inc.accounting.data = {};

new function() {
	inc.accounting.data.ListFiltersRow = function() {
		var obj = new inc.data.Row();

				
		/*
		 * @type java.lang.String
		 */
		obj.getGuid = function() { return obj.get("GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setGuid = function(value) { obj.set("GUID", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getListsGuid = function() { return obj.get("Lists GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setListsGuid = function(value) { obj.set("Lists GUID", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getPrompt = function() { return obj.get("Prompt"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setPrompt = function(value) { obj.set("Prompt", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getDataType = function() { return obj.get("Data Type"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setDataType = function(value) { obj.set("Data Type", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getQuery = function() { return obj.get("Query"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setQuery = function(value) { obj.set("Query", value); };
		
		

		return obj;
	};
};