////////////////////////////////////////////////////////////////////////////////
// 
// WARNING - DO NOT EDIT THIS FILE
//
// These data objects are generated from the database.  If you need to add 
// properties, please update the database, then re-generate.
//
////////////////////////////////////////////////////////////////////////////////
if(!inc)
	var inc = {};
if(!inc.accounting)
	inc.accounting = {};
if(!inc.accounting.data)
	inc.accounting.data = {};

new function() {
	inc.accounting.data.ListsRow = function() {
		var obj = new inc.data.Row();

				
		/*
		 * @type java.lang.String
		 */
		obj.getGuid = function() { return obj.get("GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setGuid = function(value) { obj.set("GUID", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getDisplayName = function() { return obj.get("Display Name"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setDisplayName = function(value) { obj.set("Display Name", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getSqlQuery = function() { return obj.get("SQL Query"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setSqlQuery = function(value) { obj.set("SQL Query", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getEditUrl = function() { return obj.get("Edit URL"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setEditUrl = function(value) { obj.set("Edit URL", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getAddUrl = function() { return obj.get("Add URL"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setAddUrl = function(value) { obj.set("Add URL", value); };
		
		

		return obj;
	};
};