////////////////////////////////////////////////////////////////////////////////
// 
// WARNING - DO NOT EDIT THIS FILE
//
// These data objects are generated from the database.  If you need to add 
// properties, please update the database, then re-generate.
//
////////////////////////////////////////////////////////////////////////////////
if(!inc)
	var inc = {};
if(!inc.accounting)
	inc.accounting = {};
if(!inc.accounting.data)
	inc.accounting.data = {};

new function() {
	inc.accounting.data.LogsRow = function() {
		var obj = new inc.data.Row();

				
		/*
		 * @type java.lang.String
		 */
		obj.getGuid = function() { return obj.get("GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setGuid = function(value) { obj.set("GUID", value); };
		
				
		/*
		 * @type java.util.Date
		 */
		obj.getOccured = function() { return obj.get("Occured"); };
		/*
		 * @param java.util.Date value 
		 */
		obj.setOccured = function(value) { obj.set("Occured", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getUsersGuid = function() { return obj.get("Users GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setUsersGuid = function(value) { obj.set("Users GUID", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getCodeGuid = function() { return obj.get("Code GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setCodeGuid = function(value) { obj.set("Code GUID", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getLog = function() { return obj.get("Log"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setLog = function(value) { obj.set("Log", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getDetails = function() { return obj.get("Details"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setDetails = function(value) { obj.set("Details", value); };
		
		

		return obj;
	};
};