////////////////////////////////////////////////////////////////////////////////
// 
// WARNING - DO NOT EDIT THIS FILE
//
// These data objects are generated from the database.  If you need to add 
// properties, please update the database, then re-generate.
//
////////////////////////////////////////////////////////////////////////////////
if(!inc)
	var inc = {};
if(!inc.accounting)
	inc.accounting = {};
if(!inc.accounting.data)
	inc.accounting.data = {};

new function() {
	inc.accounting.data.PaymentTypesDocumentTypesRow = function() {
		var obj = new inc.data.Row();

				
		/*
		 * @type java.lang.String
		 */
		obj.getDocumentTypesGuid = function() { return obj.get("Document Types GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setDocumentTypesGuid = function(value) { obj.set("Document Types GUID", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getPaymentTypesGuid = function() { return obj.get("Payment Types GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setPaymentTypesGuid = function(value) { obj.set("Payment Types GUID", value); };
		
		

		return obj;
	};
};