////////////////////////////////////////////////////////////////////////////////
// 
// WARNING - DO NOT EDIT THIS FILE
//
// These data objects are generated from the database.  If you need to add 
// properties, please update the database, then re-generate.
//
////////////////////////////////////////////////////////////////////////////////
if(!inc)
	var inc = {};
if(!inc.accounting)
	inc.accounting = {};
if(!inc.accounting.data)
	inc.accounting.data = {};

new function() {
	inc.accounting.data.PayrollFieldsRow = function() {
		var obj = new inc.data.Row();

				
		/*
		 * @type java.lang.String
		 */
		obj.getGuid = function() { return obj.get("GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setGuid = function(value) { obj.set("GUID", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getName = function() { return obj.get("Name"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setName = function(value) { obj.set("Name", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getPayrollFieldTypesGuid = function() { return obj.get("Payroll Field Types GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setPayrollFieldTypesGuid = function(value) { obj.set("Payroll Field Types GUID", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getDebitAccountsGuid = function() { return obj.get("Debit Accounts GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setDebitAccountsGuid = function(value) { obj.set("Debit Accounts GUID", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getCreditAccountsGuid = function() { return obj.get("Credit Accounts GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setCreditAccountsGuid = function(value) { obj.set("Credit Accounts GUID", value); };
		
		

		return obj;
	};
};