////////////////////////////////////////////////////////////////////////////////
// 
// WARNING - DO NOT EDIT THIS FILE
//
// These data objects are generated from the database.  If you need to add 
// properties, please update the database, then re-generate.
//
////////////////////////////////////////////////////////////////////////////////
if(!inc)
	var inc = {};
if(!inc.accounting)
	inc.accounting = {};
if(!inc.accounting.data)
	inc.accounting.data = {};

new function() {
	inc.accounting.data.PayrollFieldValuesRow = function() {
		var obj = new inc.data.Row();

				
		/*
		 * @type java.lang.String
		 */
		obj.getGuid = function() { return obj.get("GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setGuid = function(value) { obj.set("GUID", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getPayrollChecksGuid = function() { return obj.get("Payroll Checks GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setPayrollChecksGuid = function(value) { obj.set("Payroll Checks GUID", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getPayrollFieldsGuid = function() { return obj.get("Payroll Fields GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setPayrollFieldsGuid = function(value) { obj.set("Payroll Fields GUID", value); };
		
				
		/*
		 * @type java.math.BigDecimal
		 */
		obj.getRate = function() { return obj.get("Rate"); };
		/*
		 * @param java.math.BigDecimal value 
		 */
		obj.setRate = function(value) { obj.set("Rate", value); };
		
				
		/*
		 * @type java.math.BigDecimal
		 */
		obj.getQuantity = function() { return obj.get("Quantity"); };
		/*
		 * @param java.math.BigDecimal value 
		 */
		obj.setQuantity = function(value) { obj.set("Quantity", value); };
		
				
		/*
		 * @type java.math.BigDecimal
		 */
		obj.getTotal = function() { return obj.get("Total"); };
		/*
		 * @param java.math.BigDecimal value 
		 */
		obj.setTotal = function(value) { obj.set("Total", value); };
		
		

		return obj;
	};
};