////////////////////////////////////////////////////////////////////////////////
// 
// WARNING - DO NOT EDIT THIS FILE
//
// These data objects are generated from the database.  If you need to add 
// properties, please update the database, then re-generate.
//
////////////////////////////////////////////////////////////////////////////////
if(!inc)
	var inc = {};
if(!inc.accounting)
	inc.accounting = {};
if(!inc.accounting.data)
	inc.accounting.data = {};

new function() {
	inc.accounting.data.ReconciliationsRow = function() {
		var obj = new inc.data.Row();

				
		/*
		 * @type java.lang.String
		 */
		obj.getGuid = function() { return obj.get("GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setGuid = function(value) { obj.set("GUID", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getAccountsGuid = function() { return obj.get("Accounts GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setAccountsGuid = function(value) { obj.set("Accounts GUID", value); };
		
				
		/*
		 * @type java.util.Date
		 */
		obj.getDate = function() { return obj.get("Date"); };
		/*
		 * @param java.util.Date value 
		 */
		obj.setDate = function(value) { obj.set("Date", value); };
		
				
		/*
		 * @type java.math.BigDecimal
		 */
		obj.getStatementEndingBalance = function() { return obj.get("Statement Ending Balance"); };
		/*
		 * @param java.math.BigDecimal value 
		 */
		obj.setStatementEndingBalance = function(value) { obj.set("Statement Ending Balance", value); };
		
				
		/*
		 * @type java.math.BigDecimal
		 */
		obj.getOffBy = function() { return obj.get("Off By"); };
		/*
		 * @param java.math.BigDecimal value 
		 */
		obj.setOffBy = function(value) { obj.set("Off By", value); };
		
		

		return obj;
	};
};