////////////////////////////////////////////////////////////////////////////////
// 
// WARNING - DO NOT EDIT THIS FILE
//
// These data objects are generated from the database.  If you need to add 
// properties, please update the database, then re-generate.
//
////////////////////////////////////////////////////////////////////////////////
if(!inc)
	var inc = {};
if(!inc.accounting)
	inc.accounting = {};
if(!inc.accounting.data)
	inc.accounting.data = {};

new function() {
	inc.accounting.data.SalesTaxMembershipsRow = function() {
		var obj = new inc.data.Row();

				
		/*
		 * @type java.lang.String
		 */
		obj.getParentSalesTaxesGuid = function() { return obj.get("Parent Sales Taxes GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setParentSalesTaxesGuid = function(value) { obj.set("Parent Sales Taxes GUID", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getChildSalesTaxesGuid = function() { return obj.get("Child Sales Taxes GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setChildSalesTaxesGuid = function(value) { obj.set("Child Sales Taxes GUID", value); };
		
		

		return obj;
	};
};