////////////////////////////////////////////////////////////////////////////////
// 
// WARNING - DO NOT EDIT THIS FILE
//
// These data objects are generated from the database.  If you need to add 
// properties, please update the database, then re-generate.
//
////////////////////////////////////////////////////////////////////////////////
if(!inc)
	var inc = {};
if(!inc.accounting)
	inc.accounting = {};
if(!inc.accounting.data)
	inc.accounting.data = {};

new function() {
	inc.accounting.data.SalesTaxesRow = function() {
		var obj = new inc.data.Row();

				
		/*
		 * @type java.lang.String
		 */
		obj.getGuid = function() { return obj.get("GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setGuid = function(value) { obj.set("GUID", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getContactsGuid = function() { return obj.get("Contacts GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setContactsGuid = function(value) { obj.set("Contacts GUID", value); };
		
				
		/*
		 * @type java.lang.Boolean
		 */
		obj.getIsGroup = function() { return obj.get("Is Group"); };
		/*
		 * @param java.lang.Boolean value 
		 */
		obj.setIsGroup = function(value) { obj.set("Is Group", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getDisplayName = function() { return obj.get("Display Name"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setDisplayName = function(value) { obj.set("Display Name", value); };
		
				
		/*
		 * @type java.math.BigDecimal
		 */
		obj.getTaxRate = function() { return obj.get("Tax Rate"); };
		/*
		 * @param java.math.BigDecimal value 
		 */
		obj.setTaxRate = function(value) { obj.set("Tax Rate", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getAccountsGuid = function() { return obj.get("Accounts GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setAccountsGuid = function(value) { obj.set("Accounts GUID", value); };
		
		

		return obj;
	};
};