////////////////////////////////////////////////////////////////////////////////
// 
// WARNING - DO NOT EDIT THIS FILE
//
// These data objects are generated from the database.  If you need to add 
// properties, please update the database, then re-generate.
//
////////////////////////////////////////////////////////////////////////////////
if(!inc)
	var inc = {};
if(!inc.accounting)
	inc.accounting = {};
if(!inc.accounting.data)
	inc.accounting.data = {};

new function() {
	inc.accounting.data.TimeEntriesRow = function() {
		var obj = new inc.data.Row();

				
		/*
		 * @type java.lang.String
		 */
		obj.getGuid = function() { return obj.get("GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setGuid = function(value) { obj.set("GUID", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getEntryTypesGuid = function() { return obj.get("Entry Types GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setEntryTypesGuid = function(value) { obj.set("Entry Types GUID", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getEmployeesGuid = function() { return obj.get("Employees GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setEmployeesGuid = function(value) { obj.set("Employees GUID", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getContactsGuid = function() { return obj.get("Contacts GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setContactsGuid = function(value) { obj.set("Contacts GUID", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getTimeSheetsGuid = function() { return obj.get("Time Sheets GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setTimeSheetsGuid = function(value) { obj.set("Time Sheets GUID", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getDocumentsGuid = function() { return obj.get("Documents GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setDocumentsGuid = function(value) { obj.set("Documents GUID", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getJobsGuid = function() { return obj.get("Jobs GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setJobsGuid = function(value) { obj.set("Jobs GUID", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getDepartmentsGuid = function() { return obj.get("Departments GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setDepartmentsGuid = function(value) { obj.set("Departments GUID", value); };
		
				
		/*
		 * @type java.util.Date
		 */
		obj.getStarted = function() { return obj.get("Started"); };
		/*
		 * @param java.util.Date value 
		 */
		obj.setStarted = function(value) { obj.set("Started", value); };
		
				
		/*
		 * @type java.util.Date
		 */
		obj.getEnded = function() { return obj.get("Ended"); };
		/*
		 * @param java.util.Date value 
		 */
		obj.setEnded = function(value) { obj.set("Ended", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getDescription = function() { return obj.get("Description"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setDescription = function(value) { obj.set("Description", value); };
		
		

		return obj;
	};
};