////////////////////////////////////////////////////////////////////////////////
// 
// WARNING - DO NOT EDIT THIS FILE
//
// These data objects are generated from the database.  If you need to add 
// properties, please update the database, then re-generate.
//
////////////////////////////////////////////////////////////////////////////////
if(!inc)
	var inc = {};
if(!inc.accounting)
	inc.accounting = {};
if(!inc.accounting.data)
	inc.accounting.data = {};

new function() {
	inc.accounting.data.TimeSheetsRow = function() {
		var obj = new inc.data.Row();

				
		/*
		 * @type java.lang.String
		 */
		obj.getGuid = function() { return obj.get("GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setGuid = function(value) { obj.set("GUID", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getEmployeesGuid = function() { return obj.get("Employees GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setEmployeesGuid = function(value) { obj.set("Employees GUID", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getNumber = function() { return obj.get("Number"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setNumber = function(value) { obj.set("Number", value); };
		
				
		/*
		 * @type java.util.Date
		 */
		obj.getPeriodEnding = function() { return obj.get("Period Ending"); };
		/*
		 * @param java.util.Date value 
		 */
		obj.setPeriodEnding = function(value) { obj.set("Period Ending", value); };
		
				
		/*
		 * @type java.math.BigDecimal
		 */
		obj.getTotalHours = function() { return obj.get("Total Hours"); };
		/*
		 * @param java.math.BigDecimal value 
		 */
		obj.setTotalHours = function(value) { obj.set("Total Hours", value); };
		
				
		/*
		 * @type java.util.Date
		 */
		obj.getPeriodStarting = function() { return obj.get("Period Starting"); };
		/*
		 * @param java.util.Date value 
		 */
		obj.setPeriodStarting = function(value) { obj.set("Period Starting", value); };
		
		

		return obj;
	};
};