////////////////////////////////////////////////////////////////////////////////
// 
// WARNING - DO NOT EDIT THIS FILE
//
// These data objects are generated from the database.  If you need to add 
// properties, please update the database, then re-generate.
//
////////////////////////////////////////////////////////////////////////////////
if(!inc)
	var inc = {};
if(!inc.accounting)
	inc.accounting = {};
if(!inc.accounting.data)
	inc.accounting.data = {};

new function() {
	inc.accounting.data.TimeEntryTypesRow = function() {
		var obj = new inc.data.Row();

				
		/*
		 * @type java.lang.String
		 */
		obj.getGuid = function() { return obj.get("GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setGuid = function(value) { obj.set("GUID", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getDescription = function() { return obj.get("Description"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setDescription = function(value) { obj.set("Description", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getItemsGuid = function() { return obj.get("Items GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setItemsGuid = function(value) { obj.set("Items GUID", value); };
		
				
		/*
		 * @type java.lang.Boolean
		 */
		obj.getIsPaid = function() { return obj.get("Is Paid"); };
		/*
		 * @param java.lang.Boolean value 
		 */
		obj.setIsPaid = function(value) { obj.set("Is Paid", value); };
		
		

		return obj;
	};
};