////////////////////////////////////////////////////////////////////////////////
// 
// WARNING - DO NOT EDIT THIS FILE
//
// These data objects are generated from the database.  If you need to add 
// properties, please update the database, then re-generate.
//
////////////////////////////////////////////////////////////////////////////////
if(!inc)
	var inc = {};
if(!inc.accounting)
	inc.accounting = {};
if(!inc.accounting.data)
	inc.accounting.data = {};

new function() {
	inc.accounting.data.TransactionsRow = function() {
		var obj = new inc.data.Row();

				
		/*
		 * @type java.lang.String
		 */
		obj.getGuid = function() { return obj.get("GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setGuid = function(value) { obj.set("GUID", value); };
		
				
		/*
		 * @type java.util.Date
		 */
		obj.getDate = function() { return obj.get("Date"); };
		/*
		 * @param java.util.Date value 
		 */
		obj.setDate = function(value) { obj.set("Date", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getReferenceNumber = function() { return obj.get("Reference Number"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setReferenceNumber = function(value) { obj.set("Reference Number", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getTransactionTypesGuid = function() { return obj.get("Transaction Types GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setTransactionTypesGuid = function(value) { obj.set("Transaction Types GUID", value); };
		
		

		return obj;
	};
};