////////////////////////////////////////////////////////////////////////////////
// 
// WARNING - DO NOT EDIT THIS FILE
//
// These data objects are generated from the database.  If you need to add 
// properties, please update the database, then re-generate.
//
////////////////////////////////////////////////////////////////////////////////
if(!inc)
	var inc = {};
if(!inc.accounting)
	inc.accounting = {};
if(!inc.accounting.data)
	inc.accounting.data = {};

new function() {
	inc.accounting.data.UsersRow = function() {
		var obj = new inc.data.Row();

				
		/*
		 * @type java.lang.String
		 */
		obj.getGuid = function() { return obj.get("GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setGuid = function(value) { obj.set("GUID", value); };
		
				
		/*
		 * @type java.lang.Boolean
		 */
		obj.getIsAllowed = function() { return obj.get("Is Allowed"); };
		/*
		 * @param java.lang.Boolean value 
		 */
		obj.setIsAllowed = function(value) { obj.set("Is Allowed", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getDisplayName = function() { return obj.get("Display Name"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setDisplayName = function(value) { obj.set("Display Name", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getEmailAddress = function() { return obj.get("Email Address"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setEmailAddress = function(value) { obj.set("Email Address", value); };
		
				
		/*
		 * @type java.util.Date
		 */
		obj.getPasswordDate = function() { return obj.get("Password Date"); };
		/*
		 * @param java.util.Date value 
		 */
		obj.setPasswordDate = function(value) { obj.set("Password Date", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getPasswordHash = function() { return obj.get("Password Hash"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setPasswordHash = function(value) { obj.set("Password Hash", value); };
		
				
		/*
		 * @type java.lang.String
		 */
		obj.getEmployeesGuid = function() { return obj.get("Employees GUID"); };
		/*
		 * @param java.lang.String value 
		 */
		obj.setEmployeesGuid = function(value) { obj.set("Employees GUID", value); };
		
		

		return obj;
	};
};